import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      title: "Education Dashboard - Canada",
      welcome: "Welcome to the dashboard!",
      description: "Explore education level data between men and women in Canada.",
      barTitle: "Education Level by Gender (2024)",
      male: "Male",
      female: "Female",
      selectLevel: "Select Education Level",
      chartsTitle: "Charts Included:",
      barChart: "Bar Chart: Compares the number of men and women at different education levels for the year 2024.",
      lineChart: "Line Chart: Shows trends in educational attainment by gender from 2015 to 2024 for selected education levels.",
      note: "Please note: This data is not based on real-world statistics. It was generated by AI solely for experimental and educational purposes.",
      enjoy: "Enjoy this experience.",
      aboutTitle: "About",
      aboutParagraph1: "This dashboard was built as part of an academic project for a User Interface course at the University of Ottawa. It explores how real-world themes like education equity can be visualized and analyzed through interactive design.",
      aboutParagraph2: "As a student at the University of Ottawa, I was excited to create this project. It has been an enriching experience that blends academic learning with practical analysis bridging real-life challenges with design thinking and meaningful data visualization.",
      educationLevels: {
        highschool: "High School",
        college: "College",
        bachelor: "Bachelor's",
        master: "Master's",
        phd: "PhD"
      }
    }
  },
  fr: {
    translation: {
      title: "Tableau de bord de l'éducation - Canada",
      welcome: "Bienvenue sur le tableau de bord!",
      description: "Explorez les niveaux d'éducation entre les hommes et les femmes au Canada.",
      barTitle: "Niveau d'éducation par sexe (2024)",
      male: "Homme",
      female: "Femme",
      selectLevel: "Sélectionner le niveau d'éducation",
      chartsTitle: "Graphiques Inclus :",
      barChart: "Diagramme à barres : Compare le nombre d'hommes et de femmes à différents niveaux d'éducation pour l'année 2024.",
      lineChart: "Diagramme en ligne : Montre les tendances de l'éducation selon le sexe de 2015 à 2024 pour les niveaux sélectionnés.",
      note: "Veuillez noter : Ces données ne sont pas basées sur des statistiques réelles. Elles ont été générées par l'IA uniquement à des fins expérimentales et éducatives.",
      enjoy: "Profitez de cette expérience.",
      aboutTitle: "À propos",
      aboutParagraph1: "Ce tableau de bord a été créé dans le cadre d'un projet académique pour un cours d'interface utilisateur à l'Université d'Ottawa. Il explore comment des thèmes réels comme l'équité en matière d'éducation peuvent être visualisés et analysés grâce à un design interactif.",
      aboutParagraph2: "En tant qu'étudiante à l'Université d'Ottawa, j'ai été ravie de créer ce projet. Cela a été une expérience enrichissante qui associe apprentissage académique et analyse concrète, reliant les défis réels à la visualisation de données significatives.",
      educationLevels: {
        highschool: "Secondaire",
        college: "Collège",
        bachelor: "Baccalauréat",
        master: "Maîtrise",
        phd: "Doctorat"
      }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
